{"uuid": "1b3b366d-a1ab-44a9-bfea-93f8877f8317", "children": ["dfd7f326-a26e-4a38-a3f3-4dd4ed412895"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. \n\n", "trace": "  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 936, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 795, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\conftest.py\", line 28, in app\n    fixture = Application(browser=browser, base_url=web_config['baseUrl'])\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\fixture\\application.py\", line 11, in __init__\n    self.wd = webdriver.Firefox()\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 166, in __init__\n    self.service.start()\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1584643597419, "stop": 1584643597424}], "start": 1584643597419, "stop": 1584643597505}