{"uuid": "3e8bebf5-2e3d-48c9-aa1e-a25126b8f9fc", "children": ["f46a9403-8dd1-4c77-9e52-5f440d2961de"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. \n\n", "trace": "  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 936, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 795, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\conftest.py\", line 28, in app\n    fixture = Application(browser=browser, base_url=web_config['baseUrl'])\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\fixture\\application.py\", line 11, in __init__\n    self.wd = webdriver.Firefox()\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 166, in __init__\n    self.service.start()\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1584643596260, "stop": 1584643596264}], "start": 1584643596259, "stop": 1584643596333}