{
  "uid" : "74cabb98792bf31c",
  "name" : "test_delete_all_contacts",
  "fullName" : "test.test_contacts.test_del_all_contact#test_delete_all_contacts",
  "historyId" : "0ae3520c43657b81d94469ec46469821",
  "time" : {
    "start" : 1584644220603,
    "stop" : 1584644222344,
    "duration" : 1741
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: 'WebDriver' object has no attribute 'switch_to_alert'",
  "statusTrace" : "app = <fixture.application.Application object at 0x00000239C6F82F08>\n\n    def test_delete_all_contacts(app):\n        old_contacts = app.contacts.get_contacts_list()\n        contact = Contacts(firstname=\"Alina\", middlename=\"Ivanovna\", lastname=\"Lallala\")\n        if app.contacts.count() == 0:\n            app.contacts.add_information_of_person(contact)\n>       app.contacts.delete_all_contacts()\n\ntest\\test_contacts\\test_del_all_contact.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <fixture.contacts.ContactsHelper object at 0x00000239C6FBA7C8>\n\n    def delete_all_contacts(self):\n        wd = self.app.wd\n        self.app.return_to_home_page()\n        self.select_all_contacts()\n        # submit deletion\n        wd.find_element_by_xpath(\"//input[@value='Delete']\").click()\n>       wd.switch_to_alert().accept()\nE       AttributeError: 'WebDriver' object has no attribute 'switch_to_alert'\n\nfixture\\contacts.py:125: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "app",
    "time" : {
      "start" : 1584644220458,
      "stop" : 1584644220603,
      "duration" : 145
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "stop",
    "time" : {
      "start" : 1584644160495,
      "stop" : 1584644160495,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "afterStages" : [ {
    "name" : "stop::fin",
    "time" : {
      "start" : 1584644265846,
      "stop" : 1584644268713,
      "duration" : 2867
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test.test_contacts"
  }, {
    "name" : "suite",
    "value" : "test_del_all_contact"
  }, {
    "name" : "host",
    "value" : "ASinelnikova"
  }, {
    "name" : "thread",
    "value" : "14004-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.test_contacts.test_del_all_contact"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "110a597867b08b8d",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost/addressbook/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost.\nStacktrace:\nWebDriverError@chrome://marionette/content/error.js:175:5\nUnknownError@chrome://marionette/content/error.js:482:5\nhandleReadyState@chrome://marionette/content/listener.js:297:13\nhandleEvent@chrome://marionette/content/listener.js:263:14",
      "time" : {
        "start" : 1584644050200,
        "stop" : 1584644050200,
        "duration" : 0
      }
    }, {
      "uid" : "77874073dee62064",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.",
      "time" : {
        "start" : 1584643596836,
        "stop" : 1584643596836,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "74cabb98792bf31c.json",
  "parameterValues" : [ ]
}